language: ruby
cache: bundler
rvm:
- 2.3.0
script:
- RAILS_ENV=test bundle exec rspec
before_script:
- RAILS_ENV=test bundle exec rails db:create
- RAILS_ENV=test bundle exec rails db:migrate --trace
